apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vrcogo6xs-java-springboot
  janus-idp.io/tekton: vrcogo6xs-java-springboot
  backstage.io/kubernetes-id: vrcogo6xs-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vrcogo6xs-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
